#!/usr/bin/env bash
# author: github.com/jcaillon
# description: This script can be sourced by commands to provide convenient functions.

# ## gitlab::getProjects
#
# Returns the list of projects for the current user from the GitLab API.
#
# - $1: role _as string_:
#       The minimum role to filter the projects. Can be: `guest`, `reporter`, `developer`, `maintainer`, `owner`.
#
# Returns:
#
# - `RETURNED_ARRAY`: The list of projects.
#
# ```bash
# gitlab::getProjects "developer"
# for project in "${RETURNED_ARRAY[@]}"; do
#   echo "$project"
# done
# ```
function gitlab::getProjects() {
  :;
}
