# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  self-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/jcaillon/valet

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      # Runs our tests
      - name: Run valet tests
        run: |
          chmod +x valet
          chmod +x valet.d/commands.d/self-build.sh
          export VALET_CONFIG_ENABLE_COLORS=true
          export VALET_CONFIG_DISABLE_PROGRESS=true
          ./valet self test -C
